name: CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI - Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
